# Generated by Django 5.0.14 on 2026-02-09 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Место, в котором необходимо выполнять привычку', max_length=255, verbose_name='Место выполнения')),
                ('time', models.TimeField(help_text='Время, когда необходимо выполнять привычку', verbose_name='Время выполнения')),
                ('action', models.CharField(help_text='Действие, которое представляет собой привычка', max_length=500, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], default='daily', max_length=10, verbose_name='Периодичность')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], null=True, verbose_name='День недели')),
                ('reward', models.CharField(blank=True, max_length=255, verbose_name='Вознаграждение')),
                ('execution_time', models.PositiveIntegerField(default=120, help_text='Время, которое предположительно потратит пользователь на выполнение привычки', verbose_name='Время на выполнение (секунды)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_habit', models.ForeignKey(blank=True, help_text='Привычка, связанная с другой привычкой', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='habits.habit')),
            ],
            options={
                'verbose_name': 'Выполнение привычки',
                'verbose_name_plural': 'Выполнения привычек',
                'ordering': ['-completed_at'],
            },
        ),
    ]
