# Generated by Django 5.0.14 on 2026-02-09 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                help_text="Действие привычки", max_length=500, verbose_name="Действие"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Время на выполнение (макс. 120 сек.)",
                verbose_name="Время на выполнение (секунды)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                help_text="Место выполнения привычки",
                max_length=255,
                verbose_name="Место выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Связанная привычка",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                help_text="Время выполнения привычки", verbose_name="Время выполнения"
            ),
        ),
    ]
